sudo: false
language: node_js
node_js: "7"

env:
  global:
    - SAUCE_USERNAME=valorkin
    - SAUCE_ACCESS_KEY=aeaf806e-ad5c-484b-a8fe-4b4b9f54e99a

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run build
  - rm -rf node_modules/ng2-bootstrap
  - npm i ./dist
  - npm run test-coverage

after_success:
  - ./node_modules/.bin/codecov
  - npm run test-cross

addons:
  # sauce labs tunel connector (read more https://docs.travis-ci.com/user/sauce-connect/ )
  sauce_connect: true
  firefox: "latest"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    # required by node-gyp to build some packages
    packages:
    - g++-4.8
